import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import Provider from './components/Provider'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-white text-black dark:bg-[#090908] dark:text-white h-full selection:bg-gray-50 dark:selection:bg-gray-800`}>
        <Provider>
          <Navbar />
          <main className=''>{children}</main>
        </Provider>
      </body>
    </html>
  )
}
